version: "3.9"

services:
    postgresql:
        container_name: postgresql
        restart: always
        image: postgres:latest
        ports:
          - 5432:5432
        volumes:
          - postgresql-data:/var/lib/postgresql:Z
        env_file:
          - .env 
        networks:
          - pg_network

    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: nhatvu148@gmail.com
          PGADMIN_DEFAULT_PASSWORD: 123456789
        ports:
          - "8989:80"
        networks:
          - pg_network

    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 123456789
        ports:
          - 27017:27017
        volumes:
          - mongodb_data:/data/db

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: 123456789
          ME_CONFIG_MONGODB_SERVER: mongodb

    envoy:
        container_name: envoy
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./envoy.yaml:/etc/envoy.yaml
        expose:
          - "80"
          - "9901"
        ports:
          - "8000:80"
          - "9901:9901"

networks:
  pg_network:
    driver: bridge

volumes:
  postgresql-data:
  mongodb_data: