version: "3.9"

services:
    postgresql:
        container_name: postgresql
        restart: always
        image: postgres:latest
        ports:
          - 5432:5432
        volumes:
          - postgresql-data:/var/lib/postgresql:Z
        env_file:
          - .env 
        networks:
          - pg_network
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: nhatvu148@gmail.com
          PGADMIN_DEFAULT_PASSWORD: 123456789
        ports:
          - "8989:80"
        networks:
          - pg_network
networks:
  pg_network:
    driver: bridge
volumes:
    postgresql-data: